server:
  port: 80
spring:
  application:
    name: MI-GATEWAY-SERVER
  datasource:
    url: jdbc:mysql://127.0.0.1:10054/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
  cloud:
    nacos:
      server-addr: 47.115.130.177:8848
      discovery:
        group: MI-DEV-GROUP
  webflux:
    hiddenmethod:
      filter:
        enabled: false
  redis:
    host: 82.156.250.238
aliyun:
  captcha:
    region-id: cn-hangzhou
    access-key-id:
    access-key-secret:
    app-key:
web:
  client:
    client-id: admin-web
    client-secret: 123456
    scope: server
    password-grant-type: password
    phone-verify-code-grant-type: verify_code
    social-grant-type: social_auth
