server:
  port: 1004
  tomcat:
    max-swallow-size: 100MB
spring:
  profiles:
    active: dev
  application:
    name: MI-TOOL-SERVER
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
    nacos:
      server-addr: 47.115.130.177
      discovery:
        group: MI-DEV-GROUP
  redis:
    lettuce:
      shutdown-timeout: 3000ms
    host: 82.156.250.238
  mail:
    host: smtp.qq.com
    password:
    port: 465
    username:
    protocol: smtps
  datasource:
    url: jdbc:mysql://127.0.0.1:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
    hikari:
      max-lifetime: 300000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
sms:
  config:
    sign-name:
    template-code:

rocketmq:
  name-server: 82.156.250.238:9876
  producer:
    group: MI-TOOL-DEV-GROUP

oss:
  config:
    bucket:
      avatar: weixiaohan-avatar
      post: weixiaohan-post

