server:
  port: 1005
  max-http-header-size: 16KB
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    hikari:
      max-lifetime: 188000
  elasticsearch:
    rest:
      uris: http://82.156.250.238:9600
  profiles:
    active: dev
  redis:
    host: 82.156.250.238
  application:
    name: MI-POST-SERVER
  cloud:
    nacos:
      server-addr: 47.115.130.177
      discovery:
        group: MI-DEV-GROUP
logging:
  file:
    name: mi-post
    path: E:\code\logfile
rocketmq:
  name-server: 82.156.250.238:9876
  producer:
    group: MI-POST-DEV-GROUP