#server:
#  port: 1006
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password:
#    hikari:
#      max-lifetime: 250000
#  redis:
#    cluster:
#      nodes:
#        - 81.70.197.232:6391
#        - 81.70.197.232:6392
#        - 81.70.197.232:6393
#        - 81.70.197.232:6394
#        - 81.70.197.232:6395
#        - 81.70.197.232:6396
#  application:
#    name: MI-USER-SERVER
#  cloud:
#    nacos:
#      server-addr: 47.115.130.177
#      discovery:
#        group: MI-DEV-GROUP
#logging:
#  file:
#    name: mi-post
#    path: E:\code\logfile
#rocketmq:
#  name-server: 8.129.40.60:9876
#  producer:
#    group: MI-USER-DEV-PRODUCER
